{
 "title": "京东云-进程监控",
 "tags": [
  "阿里云",
  "Non-ali-API"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "A00_iid",
    "label": "实例ID",
    "query": {
     "query": "label_values(linux_proc_info,A00_iid)"
    }
   },
   {
    "name": "pid",
    "label": "PID",
    "query": {
     "query": "label_values(linux_proc_info{A00_iid=~\"$A00_iid\"},pid)"
    }
   },
   {
    "name": "instance",
    "label": "实例IP",
    "query": {
     "query": "label_values(linux_proc_info{A00_iid=~\"$A00_iid\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "总览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "进程监控基础信息",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "linux_proc_info{A00_iid=~\"$A00_iid\",pid=~\"$pid\"} * on (A00_iid,pid) group_left linux_proc_durn"
    }
   ]
  },
  {
   "title": "进程信息明细",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "进程分类内存占用量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "linux_proc_memory_rss{A00_iid=~\"$A00_iid\",pid=~\"$pid\"}",
     "legendFormat": "{{pid}}：常驻内存"
    },
    {
     "expr": "linux_proc_memory_vms{A00_iid=~\"$A00_iid\",pid=~\"$pid\"}",
     "legendFormat": "{{pid}}：虚拟内存"
    },
    {
     "expr": "linux_proc_memory_shared{A00_iid=~\"$A00_iid\",pid=~\"$pid\"}",
     "legendFormat": "{{pid}}：共享内存"
    },
    {
     "expr": "linux_proc_memory_swap{A00_iid=~\"$A00_iid\",pid=~\"$pid\"}",
     "legendFormat": "{{pid}}：交换内存"
    },
    {
     "expr": "linux_proc_memory_data{A00_iid=~\"$A00_iid\",pid=~\"$pid\"}",
     "legendFormat": "{{pid}}：除代码内存"
    },
    {
     "expr": "linux_proc_memory_text{A00_iid=~\"$A00_iid\",pid=~\"$pid\"}",
     "legendFormat": "{{pid}}：代码内存"
    }
   ]
  },
  {
   "title": "进程实际内存占用比例",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "linux_proc_memory_percent{A00_iid=~\"$A00_iid\",pid=~\"$pid\"}",
     "legendFormat": "{{pid}}：内存占比"
    }
   ]
  },
  {
   "title": "进程CPU占用 （单核为100%计算，超过100%为使用多核）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(linux_proc_cpu_user{A00_iid=~\"$A00_iid\",pid=~\"$pid\"}[5m])",
     "legendFormat": "{{pid}}：用户cpu占比"
    },
    {
     "expr": "irate(linux_proc_cpu_system{A00_iid=~\"$A00_iid\",pid=~\"$pid\"}[5m])",
     "legendFormat": "{{pid}}：系统cpu占比"
    },
    {
     "expr": "irate(linux_proc_cpu_iowait{A00_iid=~\"$A00_iid\",pid=~\"$pid\"}[5m])",
     "legendFormat": "{{pid}}：iowait_cpu占比"
    },
    {
     "expr": "irate(linux_proc_cpu_children_user{A00_iid=~\"$A00_iid\",pid=~\"$pid\"}[5m])",
     "legendFormat": "{{pid}}：子进程用户_cpu占比"
    },
    {
     "expr": "irate(linux_proc_cpu_children_system{A00_iid=~\"$A00_iid\",pid=~\"$pid\"}[5m])",
     "legendFormat": "{{pid}}：子进程系统_cpu占比"
    },
    {
     "expr": "linux_proc_cpu_percent{A00_iid=~\"$A00_iid\",pid=~\"$pid\"}/100",
     "legendFormat": "{{pid}}：总使用CPU占比"
    }
   ]
  },
  {
   "title": "ECS CPU总使用率（所有核平均）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$instance\",mode=\"idle\"}[3m])) by (instance))*100",
     "legendFormat": "cpu_total"
    }
   ]
  },
  {
   "title": "进程IOPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "irate(linux_proc_io_read_count{A00_iid=~\"$A00_iid\",pid=~\"$pid\"}[5m])",
     "legendFormat": "{{pid}}：读IO"
    },
    {
     "expr": "irate(linux_proc_io_write_count{A00_iid=~\"$A00_iid\",pid=~\"$pid\"}[5m])",
     "legendFormat": "{{pid}}：写IO"
    }
   ]
  },
  {
   "title": "进程IO读写",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(linux_proc_io_read_bytes{A00_iid=~\"$A00_iid\",pid=~\"$pid\"}[5m])",
     "legendFormat": "{{pid}}：读字节"
    },
    {
     "expr": "irate(linux_proc_io_write_bytes{A00_iid=~\"$A00_iid\",pid=~\"$pid\"}[5m])",
     "legendFormat": "{{pid}}：写字节"
    }
   ]
  },
  {
   "title": "文件描述符与线程",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "linux_proc_num_open_files{A00_iid=~\"$A00_iid\",pid=~\"$pid\"}",
     "legendFormat": "{{pid}}：打开文件数"
    },
    {
     "expr": "linux_proc_num_fds{A00_iid=~\"$A00_iid\",pid=~\"$pid\"} / linux_proc_num_fds_limit{A00_iid=~\"$A00_iid\",pid=~\"$pid\"}",
     "legendFormat": "{{pid}}：文件描述符上限占比"
    },
    {
     "expr": "linux_proc_num_fds{A00_iid=~\"$A00_iid\",pid=~\"$pid\"}",
     "legendFormat": "{{pid}}：打开文件描述符"
    },
    {
     "expr": "linux_proc_num_threads{A00_iid=~\"$A00_iid\",pid=~\"$pid\"}",
     "legendFormat": "{{pid}}：线程数"
    },
    {
     "expr": "linux_proc_num_children{A00_iid=~\"$A00_iid\",pid=~\"$pid\"}",
     "legendFormat": "{{pid}}：子进程"
    },
    {
     "expr": "linux_proc_num_fds_limit{A00_iid=~\"$A00_iid\",pid=~\"$pid\"}",
     "legendFormat": "{{pid}}：文件描述符上限"
    }
   ]
  }
 ]
}